### ISSUE TITLE
Authentication fails in Chrome with "Invalid State" error message

### ISSUE THREAD

**Issue by hrabur** [morulay/shiro-aad#3]
If Chrome has flag #cookies-without-same-site-must-be-secure (and #same-site-by-default-cookies) enabled then the POST with the id_token fails with error message "Invalid State", because Chrome don't send the `state` and `nonce` cookies.

If not enabled the aforementioned flags then authentication works fine, but you can see in Chrome the following Issue:

> Mark cross-site cookies as Secure to allow them to be sent in cross-site requests
> 
> Cookies marked with SameSite=None must also be marked with Secure to get sent in cross-site requests. This behavior protects user data from being sent over an insecure connection.
> 
> Resolve this issue by updating the attributes of the cookie:
> - Specify SameSite=None and Secure if the cookie should be sent in cross-site requests. This enables third-party use.
> - Specify SameSite=Strict or SameSite=Lax if the cookie should not be sent in cross-site requests

As the Chrome issue report suggests the possible fix could be to mark `state` and `nonce` cookies as `Secure`

**Comment by morulay** [comment]
Thanks. Fix is working fine. 
Do you have plans to release a version?

**Comment by hrabur** [comment]
Thanks. Fix is working fine.
Do you have plans to release a version?
